language: go
sudo: false
go:
  - 1.9.x

git:
  depth: 3

before_install:
  - sudo apt-get -qq update


install: true


go_import_path: github.com/fnzv/net-Shield

script:
- go get github.com/BurntSushi/toml
- go build shield.go
- go build config-shield.go
